### PR TITLE
Typescript signature doesn't match the javascript one

### PR DESCRIPTION
**Pull request by Neku**

### CODE REVIEW

**Comment by explicitcall** [comment]
can this be looked into? A very trivial change, hope this can be merged straight away;

**Comment by maxpaj** [comment]
Can this be merged?

**Comment by explicitcall** [comment]
Hi @sandrinodimattia, could you please have a look?

**Comment by sandrinodimattia** [comment]
This was released as 1.2.1 from #25 
Sorry for the delay on getting this released.

**Pull request closed without merging**
