### PR TITLE
fixed typescript definitions and added tests

### PR DESCRIPTION
**Pull request by igorsechyn**
The typescript definition of `hapiJwt2KeyAsync` was wrong and I tried to fix base on the current implementation. I also added a test to verify that the definition is actually correct. It should catch any changes to the implementation. 

Other definitions may be wrong as well, I was only blocked by `hapiJwt2KeyAsync`. So maybe worth checking them as well.

### CODE REVIEW

**Comment by igorsechyn** [comment]
Just saw there is another PR to fix typings https://github.com/auth0/node-jwks-rsa/pull/80. Happy to rebase off it, when its merged to add tests

**Comment by luisrudge** [comment]
@igorsechyn yeah. we should totally merge both of them.

**Comment by igorsechyn** [comment]
@luisrudge how do you want to proceed? Merge #80 first and I'll rebase this one off master?

**Comment by luisrudge** [comment]
@igorsechyn perfect. I asked for a tiny change. I'll merge it once it's fixed and then you can rebase your PR. Thanks for the help!

**Comment by luisrudge** [comment]
@igorsechyn #80 is done.

**Comment by igorsechyn** [comment]
@luisrudge I rebased off master.

**Comment by luisrudge** [comment]
Thanks @igorsechyn for all the help!

**Pull request merged**
