### PR TITLE
full JWK/JWS support

### LINKED ISSUE #11: The JWKS endpoint did not contain any signing keys
Looking closer within **JwksClient.js**, it seems to not filter out the keys properly. By default, the **kty** value in this was **RSA**, but our Ping implementation used **EC** keys.  I swapped that, but the following code produces an undefined list of "keys"...

`
var signingKeys = keys.filter(function (key) {
          return key.use === 'sig' && key.kty === 'EC' && key.kid && (key.x5c && key.x5c.length || key.n && key.e);
        }).map(function (key) {
          if (key.x5c && key.x5c.length) {
            return { kid: key.kid, nbf: key.nbf, publicKey: (0, _utils.certToPEM)(key.x5c[0]) };
          } else {
            return { kid: key.kid, nbf: key.nbf, rsaPublicKey: (0, _utils.rsaPublicKeyToPEM)(key.n, key.e) };
          }
        });
`

This is our JWKS file example:
`{"keys":[{"kty":"EC","kid":"k9","use":"sig","alg":"ES512","x":"<value>","y":"<value>","crv":"P-521"},{"kty":"EC","kid":"k8","use":"sig","alg":"ES384","x":"<value>","y":"<value>","crv":"P-384"},{"kty":"EC","kid":"k7","use":"sig","alg":"ES256","x":"<value>","y":"<value>","crv":"P-256"},{"kty":"EC","kid":"k3","use":"sig","alg":"ES512","x":"<value>","y":"<value>","crv":"P-521"},{"kty":"EC","kid":"k2","use":"sig","alg":"ES384","x":"<value>","y":"<value>","crv":"P-384"},{"kty":"EC","kid":"k1","use":"sig","alg":"ES256","x":"<value>","y":"<value>","crv":"P-256"},{"kty":"EC","kid":"jx","use":"sig","alg":"ES512","x":"<value>","y":"<value>","crv":"P-521"},{"kty":"EC","kid":"jw","use":"sig","alg":"ES384","x":"<value>","y":"<value>","crv":"P-384"},{"kty":"EC","kid":"jv","use":"sig","alg":"ES256","x":"<value>","y":"<value>","crv":"P-256"}]}`

### LINKED ISSUE #40: Support for other algorithms?
I'm currently looking for a library facilitating getting the keys from a JWKS endpoint. However, in our application we're using the ES256 algorithm for signing. I'm thus a little bit bummed to notice this library, which would seem to be a perfect fit for the problem I'm trying to solve, has a hard coded check on the key type.

I'm wondering:

- as to why there's only support for the RSA algorithm
- if there are plans to support other algorithms in the future
- if you know any alternatives (after some extensive Googling, I have found none)
- whether you would be open to a PR supporting other algorithms

Many thanks,
Thomas

### LINKED ISSUE #50: Support for EC JWK format?
We've been using this library to obtain the key matching the supplied kid from a 3rd party system that just moved to use EC format JWK rather than RS.

The library returns null for the key if the format isn't RS256 without any other logging, which took us a while to identify the problem.

Is there a recommended approach for also supporting EC keys for lookup from a JSON Web Key Set URL?

### PR DESCRIPTION
**Pull request by panva**
### Description
This PR contains support for all currently registered JWK types and JWS Algorithms.

### References
- #170, I took the liberty of rebasing #170, further cleaning up unnecessary dependencies (moved them to devDependencies)
- [https://github.com/auth0/node-jwks-rsa/issues?q=is%3Aissue+ec](https://github.com/auth0/node-jwks-rsa/issues?q=is%3Aissue+ec+sort%3Aupdated-desc)

* [x]  This change adds test coverage for new/changed/fixed functionality

### Checklist
* [x]  I have added documentation for new/changed functionality in this PR or in auth0.com/docs
* [x]  All active GitHub checks for tests, formatting, and security are passing
* [x]  The correct base branch is being used, if not `master`

Closes #170
Closes #40
Closes #50
Closes #11

Credit goes to @ivn-cote for his work on #170. Note that, just like #170 this warrants a new major release due to dependency's node runtime requirements, the removal of `nbf` passthrough (`nbf` on a JWK isn't standardized) as well as proper JWK parsing rules put forth by the inclusion of `jose`.

### CODE REVIEW

**Comment by ivn-cote** [comment]
Thank you for pushing the change!

**Review by davidpatrick — APPROVED** [review]

**Review by adamjmcgrath — DISMISSED** [review]

**Review by davidpatrick — DISMISSED** [review]
Rebased with master, resolved conflicts on the package lock

**Review by davidpatrick — APPROVED** [review]

**Comment by ivn-cote** [comment]
@davidpatrick thanks for the pushing the project forward! I see there is a next milestone https://github.com/auth0/node-jwks-rsa/milestone/7?closed=1
Can you maybe push beta version of the package to NPM please?

**Comment by davidpatrick** [comment]
@ivn-cote sorry for the delay on this, we are moving forward with this release this week

**Comment by krazar** [comment]
@davidpatrick Do you still plan to make the release this week ? 
Thank you

**Pull request merged**
