### PR TITLE
Added timeout with default value of 30s

### PR DESCRIPTION
**Pull request by Cooke**
### Description

The purpose of this pull request is to add a timeout (with default value) which applies to the request for fetching keys. 

The introduction of the timeout setting isn't itself breaking but the default value of 30s could be considered breaking, though it should be a sane value that everyone could live with.

### References
Issue #131 

### Testing

No tests have been added. 

This change depends on the timeout functionality of the request lib. 

Manual verification has been done and auto tests have been executed with npm test.

### Checklist

- [ yes ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ yes ] All active GitHub checks for tests, formatting, and security are passing
- [ not sure ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by davidpatrick** [comment]
Hey @Cooke thanks for the contribution.  We are currently migrating off of request because of the libraries deprecation.  We will be moving to axios and exposing the axios config options which will allow you to set the timeout.  https://github.com/auth0/node-jwks-rsa/pull/134

We can move forward with this PR, but its use would break in PR #134.  Let me know if you are able to wait.

Thanks

**Comment by Cooke** [comment]
@davidpatrick we can wait. We are already using our own fork in the meanwhile. Thank you

**Comment by apumb** [comment]
Hi @davidpatrick, Just wondering if there was a timeframe for moving to axios?  This will solve some issues we're facing and wondering how best to proceed? 
Thanks

**Comment by Cooke** [comment]
@davidpatrick that should hopefully do it. But you should better check it. Also I think I screwed up the ticket references, sorry.

**Comment by apumb** [comment]
Thanks @davidpatrick, this is awesome!!

**Comment by davidpatrick** [comment]
@Cooke  I've merged in the request dep changes, can you rebase this with master? That should resolve the conflicts

**Pull request merged**
