### PR TITLE
Integrate with passport-jwt

### PR DESCRIPTION
**Pull request by gconnolly**
I created an integration with passport/passport-jwt, so I thought I would share it. It includes the integration as well as an example.

### CODE REVIEW

**Comment by sandrinodimattia** [comment]
Thanks for the PR. Can you add some tests?

**Comment by gconnolly** [comment]
@sandrinodimattia tests added. Getting the error messages to bubble up to validate expectations is a little strange with passport + express, but it gets the job done.

**Comment by gconnolly** [comment]
@sandrinodimattia is there anything I can do to move this towards a merge?

**Comment by rassokhin-s** [comment]
Hey guys, are there any plans to merge this PR?

**Comment by gconnolly** [comment]
I sort of feel like maybe I shouldn't have spent my time to write the tests?

**Comment by xmlking** [comment]
@gconnolly thanks for your contribution. I am planing to use your PR along with @nestjs/passport 
do you have  your version on NPM ?

**Comment by tdespenza** [comment]
"So when is this getting merge?"

**Comment by xmlking** [comment]
@gconnolly I send you PR with latest upstream merged. Also now exposing  ` function passportJwtSecret(options: JwksRsa.Options): ExpressJwt.SecretCallback;` in  `index.d.ts` for easy import.

**Comment by SeanLMcCullough** [comment]
Almost a year later and still waiting...

**Comment by gconnolly** [comment]
@xmlking Somehow I missed the notification of your PR 🤷‍♂️ . Merged! thank you.

I noticed several version changes to the package.json. I am having difficulty tracing them back to the corresponding upstream commit, and they are not currently in master.

CC @SeanLMcCullough thanks for the ping. Hopefully we get a merge before its first birthday 🍰

**Comment by gconnolly** [comment]
reverted some unintentional dependency changes. Will continue to maintain this PR, while there are still people inquiring about it.

**Comment by EtienneK** [comment]
Please merge this. Would be great to have a working example.

**Comment by EtienneK** [comment]
Please merge this. Would be great to have a working example.

**Comment by garyevari** [comment]
This has been waiting for over a year... any chance this is going to happen?

**Comment by taurenk** [comment]
@gconnolly any plans to merge this soon?

**Comment by cspicuzza** [comment]
please merge 🙏

**Comment by sonman1** [comment]
This worked well for me. Thanks for the work on the PR! Looking forward to seeing it merged.

**Comment by jajaperson** [comment]
If anyone wants to use this ***NOW***, I've made a fork of this fork ([jajaperson/node-rwks-rsa](https://github.com/jajaperson/node-rwks-rsa)) with the `prePublish` script switched to a `prepare` script, so you can install it via `npm install jajaperson/node-rwks-rsa` or `npm install github:jajaperson/node-rwks-rsa`.

**Comment by svantetobias** [comment]
This would be really useful. Waiting for it.

**Comment by gperdomor** [comment]
please merge this

**Comment by maciejmatu** [comment]
@Mutmatt @sandrinodimattia @lbalmaceda @gconnolly Not sure who is the owner/maintainer of this repo, but is there any work to be done on this ticket, and who could merge it when it's finished. If there are some updates needed I can spare some time to work on it, as it would be nicer to stay with the official package, without using forked repos 😄

**Comment by murbanowicz** [comment]
@lbalmaceda @damieng @Mutmatt @cocojoe @sandrinodimattia Could you or any of your colleagues finally merge this?

**Comment by blakedietz** [comment]
What's going on with this ticket. Someone? Anyone? Hellooooo?

What are the next steps to make this bad boy merge?

**Comment by Mutmatt** [comment]
Oye! I can check on this on Monday. Not trying to pass the buck, however, this repo isn't owned or maintained by my team. We just used it. I'll see if I can get the group some traction

**Comment by jajaperson** [comment]
@Mutmatt any progress?

**Comment by Mutmatt** [comment]
We are actively discussing this PR internally and certainly value the effort, time, and energy everyone has contributed here. I don’t yet have an update to report but will provide one when I am able to.

**Comment by gconnolly** [comment]
😎

**Pull request merged**
