### PR TITLE
Add fastify integration

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Adds an integration for Fastify. I'll be adding unit tests tomorrow. Ref https://github.com/fastify/fastify-jwt/pull/10 https://github.com/fastify/fastify-jwt/issues/8

### CODE REVIEW

**Comment by lgomez** [comment]
Is there anything we can do to get this accepted and merged?

**Comment by Ethan-Arrowood** [comment]
I think this repo might not be very active haha

**Comment by cocojoe** [comment]
@Ethan-Arrowood thanks for the contribution, you mentioned some tests?

**Comment by Ethan-Arrowood** [comment]
Hi @cocojoe Ahh yes I did; I'll push some updates soon.

**Comment by sandrinodimattia** [comment]
Please also rebase your changes 👍

**Comment by cocojoe** [comment]
@Ethan-Arrowood any updates on this? Thx

**Comment by Ethan-Arrowood** [comment]
Hi apologies for the delay I had an incredible busy week finishing up final assignments for Uni. I'll try to hash this out today.

**Comment by Ethan-Arrowood** [comment]
Alright rebased and fixed some merge conflicts. Started working on tests. Not sure what I should be testing so I'm using the existing tests as a reference. I also don't think Fastify works in the `supertest` `request()` method so I gotta see what to do about that.

**Comment by degrammer** [comment]
Hi @Ethan-Arrowood  we really appreciate this work, I was reviewing the integration of your changes with a local fastify server, since I don't have any experience with fastify, can you help us to clarify the implementation details and add it as an example on our **examples** directory ?
With this code I'm always getting this message: **only RS256 is supported**  

`
const fastify = require('fastify')();
const fastifyJwt = require('fastify-jwt');
const jwksRsa = require('jwks-rsa');

fastify.post('/signup', (request, reply) => {
  reply.jwtSign(request.body, function (err, token) {
    return reply.send(err || { 'token': token })
  })
})

// Run the server!
const start = async () => {
  try {
    fastify.register(fastifyJwt, { 
      secret: jwksRsa.fastifyJwtSecret({
        jwksUri: 'http://localhost/.well-known/jwks.json'
      }),
      algorithms: ['RS256']
    })
    await fastify.listen(9000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
`

**Comment by Ethan-Arrowood** [comment]
Will work on an example now.

**Comment by Ethan-Arrowood** [comment]
Okay I'm unsure how to mock a jwks locally, but this code _should_ work. It is pretty much what you sent just the register block is moved to outside the `start` method. I was using this in a project a while back with Auth0 as well as some scoping authz functionality. The project went stagnant about 4-5 months ago so i don't know how well its working anymore. If this demo still doesn't work I'll see what I can make happen from scratch.

Sorry I've been touch and go with this PR. I pushed it to the back of my mind a while back, so now I'm just trying to remember how to get it all working again.

**Comment by degrammer** [comment]
Thank you @Ethan-Arrowood  I will review it.

**Comment by vcanales** [comment]
> Hi @Ethan-Arrowood we really appreciate this work, I was reviewing the integration of your changes with a local fastify server, since I don't have any experience with fastify, can you help us to clarify the implementation details and add it as an example on our **examples** directory ?
> With this code I'm always getting this message: **only RS256 is supported**

Had the same issue, I had to add `decode: { complete: true }` to the `options` object to get the headers along with the payload of the token. This seems a bit stale, may I chime in with a working implementation? There's something else to consider in that the `decode` parameter is not returned if the token is invalid, so the "Only RS256 is supported" error is misleading in that case.

**Comment by Ethan-Arrowood** [comment]
@vcanales I'll go through this tonight! Thank you

**Comment by Ethan-Arrowood** [comment]
@vcanales looks like you made a pr to the master branch on my fork. Can you make your PR against the `add-fastify` branch on my fork instead please?

**Comment by Ethan-Arrowood** [comment]
I have rebased my branch against origin master. Currently awaiting changes from @vcanales

**Comment by vcanales** [comment]
Hello, @degrammer! I think we've addressed your concerns on previous comments with the latest changes. It would be amazing if you could take some time to re-review this!

**Comment by dnlup** [comment]
Are there any news on this? Can I help in any way?

**Comment by vcanales** [comment]
Gone off my own way and created a fork:

- https://github.com/vcanales/fastify-authz-secret-provider
- https://www.npmjs.com/package/fastify-authz-secret-provider

**Comment by tnguyen14** [comment]
Thanks @vcanales for the fork. Would've been great if this work was integrated into this library.

**Pull request closed without merging**
