### PR TITLE
Release 2.0.3

### PR DESCRIPTION
**Pull request by davidpatrick**
## [2.0.3] - (2021-04-20)

**Fixed**
- Fix retrieveSigningKeys error [\#242](https://github.com/auth0/node-jwks-rsa/pull/237) ([davidpatrick](https://github.com/davidpatrick))

**Security**
- Bump jose from 2.0.3 to 2.0.5 [\#244](https://github.com/auth0/node-jwks-rsa/pull/244) ([dependabot](https://github.com/dependabot))

### CODE REVIEW

**Review by adamjmcgrath — APPROVED** [review]

**Comment by nalham** [comment]
When is this expected to release? Looking forward to https://github.com/auth0/node-jwks-rsa/pull/244 fixing `npm audit`.

**Review by panva — CHANGES_REQUESTED** [review]
@davidpatrick @adamjmcgrath please update the jose entry in package.json as well. Changes in package-lock.json make no difference to users of this module.

**Comment by adamjmcgrath** [comment]
> When is this expected to release? Looking forward to #244 fixing npm audit.

@nalham `npm audit --fix` will fix the jose dependency in your `package-lock.json`

@panva - https://github.com/auth0/node-jwks-rsa/pull/247

**Review by panva — COMMENTED** [review]
let's rebase and we're good here.

**Review by panva — APPROVED** [review]

**Pull request merged**
