### PR TITLE
style: no extra semi

### PR DESCRIPTION
**Pull request by neutiyoo**
### Description
This PR removes extra semicolons 

### Reference
https://eslint.org/docs/rules/no-extra-semi

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by lbalmaceda — CHANGES_REQUESTED** [review]
I'm sure those semicolons are supposed to be there, according to [this rule](https://eslint.org/docs/rules/semi) in the eslint file https://github.com/auth0/node-jwks-rsa/blob/master/.eslintrc#L24. 

Looks like the script you should run is `npm run lint`, but it's not tied to the pre-commit hook. @davidpatrick can you review this, please?

**Comment by neutiyoo** [comment]
hello, thank you for the review! Let me clarify the function declaration.

Function declaration is not a statement. Therefore, semicolons after function declarations are not necessary.

Here are references: 
- https://www.ecma-international.org/ecma-262/10.0/index.html#sec-ecmascript-language-functions-and-classes
- https://stackoverflow.com/questions/1834642/why-should-i-use-a-semicolon-after-every-function-in-javascript
- https://mariusschulz.com/articles/function-definitions-in-javascript

>I'm sure those semicolons are supposed to be there, according to this rule in the eslint file https://github.com/auth0/node-jwks-rsa/blob/master/.eslintrc#L24.
The rule forces you to have semicolons for *statements* but it doesn't tell that there are extra semicolons.
Also, you can notice the inconsistent styles in the codebase. For example, `prepadSigned` doesn't have extra semicolons but `certToPEM` does.

```
export function certToPEM(cert) {
  cert = cert.match(/.{1,64}/g).join('\n');
  cert = `-----BEGIN CERTIFICATE-----\n${cert}\n-----END CERTIFICATE-----\n`;
  return cert;
};

function prepadSigned(hexStr) {
  const msb = hexStr[0];
  if (msb < '0' || msb > '7') {
    return `00${hexStr}`;
  }
  return hexStr;
}
```

To prevent this kind of misunderstanding, we can add `no-extra-semi` rule.

**Comment by neutiyoo** [comment]
Hello, thank you for the review! 

Unlike `FunctionExpression`, semicolons after `FunctionDeclaration` are not necessary.
e.g.
```
// A function declaration of a function named multiply:
function multiply(x, y) {
    return x * y;
}

// A function expression assigned to the variable multiply:
var multiply = function (x, y) {
    return x * y;
};
```

Here are the references: 
- https://www.ecma-international.org/ecma-262/10.0/index.html#sec-ecmascript-language-functions-and-classes
- http://kangax.github.io/nfe/
- https://stackoverflow.com/questions/1634268/explain-the-encapsulated-anonymous-function-syntax

Also, you can notice the inconsistency in the codebase. For example, `certToPEM` does have an extra semicolon but `prepadSigned` doesn't.

```
export function certToPEM(cert) {
  cert = cert.match(/.{1,64}/g).join('\n');
  cert = `-----BEGIN CERTIFICATE-----\n${cert}\n-----END CERTIFICATE-----\n`;
  return cert;
};

function prepadSigned(hexStr) {
  const msb = hexStr[0];
  if (msb < '0' || msb > '7') {
    return `00${hexStr}`;
  }
  return hexStr;
}
```

>I'm sure those semicolons are supposed to be there, according to this rule in the eslint file https://github.com/auth0/node-jwks-rsa/blob/master/.eslintrc#L24.

The `semi` rule forces you to have semicolons for statements but it doesn't tell that there are extra semicolons.

To prevent this kind of misunderstanding and remove the inconsistency, I added `no-extra-semi` rule.

**Comment by neutiyoo** [comment]
Hello, thank you for the review! 

Unlike `FunctionExpression`, semicolons after `FunctionDeclaration` are not necessary.
e.g.
```
// A function declaration of a function named multiply:
function multiply(x, y) {
    return x * y;
}

// A function expression assigned to the variable multiply:
const multiply = function (x, y) {
    return x * y;
};
```

Here are the references: 
- https://www.ecma-international.org/ecma-262/10.0/index.html#sec-ecmascript-language-functions-and-classes
- http://kangax.github.io/nfe/
- https://stackoverflow.com/questions/1634268/explain-the-encapsulated-anonymous-function-syntax

Also, you can notice the inconsistency in the codebase. For example, `certToPEM` does have an extra semicolon but `prepadSigned` doesn't.

```
export function certToPEM(cert) {
  cert = cert.match(/.{1,64}/g).join('\n');
  cert = `-----BEGIN CERTIFICATE-----\n${cert}\n-----END CERTIFICATE-----\n`;
  return cert;
};

function prepadSigned(hexStr) {
  const msb = hexStr[0];
  if (msb < '0' || msb > '7') {
    return `00${hexStr}`;
  }
  return hexStr;
}
```

>I'm sure those semicolons are supposed to be there, according to this rule in the eslint file https://github.com/auth0/node-jwks-rsa/blob/master/.eslintrc#L24.

The `semi` rule can't tell you that there are extra semicolons but `no-extra-semi` can.

To prevent this kind of misunderstanding and remove the inconsistency, I added `no-extra-semi` rule.

**Comment by lbalmaceda** [comment]
I agree the actual fix should be on the eslint file rules. Lets wait on @davidpatrick to evaluate how we can include this as part of the commit process, so following PRs include these without extra effort from the developer.

**Review by davidpatrick — APPROVED** [review]

**Pull request merged**
