### PR TITLE
fixed index.d.ts for exposing functions

### PR DESCRIPTION
**Pull request by mslourens**

### CODE REVIEW

**Comment by MHeironimus** [comment]
This should fix issue #21.

**Comment by kati-frantz** [comment]
Please merge changes, no express applications can use the package with this error ! Thanks !

**Comment by mccool** [comment]
Just echoing @kati-frantz. What are the plans to merge these changes?

**Comment by sandrinodimattia** [comment]
Thanks for the PR @mslourens - this was released as 1.2.1
Sorry for the delay on getting this released.

**Pull request merged**
