### PR TITLE
Possible typo: JwksClient.getSigningKey()

### PR DESCRIPTION
**Pull request by sjawhar**
## Purpose
I think there is a typo the JwksClient library. `JwksClient.getSigningKey()` is not defined as a class method according to ES6, but rather as a class property. Besides being inconsistent, it's making it harder for me to stub the method for tests :) This is because getSigningKey is not defined on JwksClient.prototype, but rather `this.getSigningKey` gets defined as a function in the constructor.

### CODE REVIEW

**Comment by QuantumLove** [comment]
:+1:

**Comment by lbalmaceda** [comment]
Can you please evaluate @stevehobbsdev?

**Comment by stevehobbsdev** [comment]
Looks good at a glance but just in case, I cloned it to run the tests and they fail.

Turns out there's also a bit of logic in the constructor that overwrites what `getSigningKey` is and the main reason why `getSigningKey` was defined as a field function rather than a class method:

https://github.com/auth0/node-jwks-rsa/blob/f301e1df759e5968e824fbe8d191dfd1751b9fba/src/JwksClient.js#L28-L33

This whole mechanism is a bit weird and I would encourage it to be rewritten to improve understanding.

**Comment by davidpatrick** [comment]
@sjawhar because of the way the wrappers interact with `getSigningKey`, it will unfortunately not be as simple as turning it into a class property.  Some more work will need to be done with how the rateLimit and cache wrappers interact with it.  This work is welcome, but if you don't have the bandwidth for it we will close this PR until further notice.

**Pull request closed without merging**
